from typing import TypedDict
from langgraph.graph import StateGraph, START, END
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_openai import ChatOpenAI
from langchain_core.runnables.graph import MermaidDrawMethod
import os
from dotenv import load_dotenv

load_dotenv()
os.environ["PYPPETEER_CHROMIUM_REVISION"] = "1263111"
os.environ["OPENAI_API_KEY"]="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"

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)

#1. Define shared state
class AgentState(TypedDict):
   query: str
   decision: str
   response: str

#2. Nodes
def classify_node(state: AgentState) -> AgentState:
    """
    LLM decides if the query is clear or needs clarification.
    """
    query = state["query"]

    prompt = f"""
    Classify the user query as:
    - clear
    - unclear
        Query: {query}

        Respond with only one word: "clear" or "unclear".
        """
    decision = llm.invoke(prompt).content.strip().lower()

    print(f"LLM Decision: {decision}")

    return {
        **state,
        "decision": decision,
    }

def answer_node(state: AgentState) -> AgentState:
    prompt = f"""Answer the following question clearly and concisely: {state['query']}"""
    answer = llm.invoke(prompt)
    return {
        **state,
        "response": f"Answering clearly: {state['query']} -> [This is a clear and complete answer generated by the LLM.]"
    }

def clarify_node(state: AgentState) -> AgentState:
    return {
        **state,
        "response": f"Can you clarify your question: {state['query']} -> [This is a request for more information generated by the LLM.]"
    }

#3. Router
def route(state: AgentState) -> str:
   return state["decision"]

#4. Build the graph
workflow = StateGraph(AgentState)
workflow.add_node("classify", classify_node)
workflow.add_node("answer", answer_node)
workflow.add_node("clarify", clarify_node)

workflow.add_edge(START, "classify")

workflow.add_conditional_edges(
    "classify",
    route,
    {
        "clear": "answer",
        "unclear": "clarify"
    }
)
workflow.add_edge("answer", END)
workflow.add_edge("clarify", END)

#5. Compile
app = workflow.compile()

#Genrete the graph visualization
graph_image = app.get_graph().draw_mermaid_png(
    draw_method=MermaidDrawMethod.PYPPETEER
    )
with open("research-clarify-answer.png", "wb") as f:    
    f.write(graph_image)   

#6. Run the graph with an example query
result = app.invoke({
    "query": "Explain the theory of relativity in simple terms.",
    "decision": "",
    "response": "",
    })

print("Final Result:",result["response"])